from setup.numerate import autoset

mode = ADD_TO_END, CREATE_NEW = autoset(2)
PATH, FILE = autoset(2)
method = ROUTER, NET = autoset(2)
# типы поиска ошибок в системном логе
# ERRORS_ONLY - ищем только ошибки
# ERROR_TAGS - ищем признаки ошибок
error_types = ERRORS_ONLY, ERROR_TAGS = autoset(2)

ADD_ACTION, \
    DEL_ACTION, \
    IMPORT_ACTION, \
    EXPORT_ACTION, \
    PURGE_ACTION \
    = autoset(5)


# Генерируем коды для различных уровней прерываний меню в Telegram
LEVELS = MAIN_MENU, \
         VPN_MENU, VPN_INTERFACE_LIST_SHOW, \
         VPN_HOST_DETAIL, VPN_HOSTS_ACTIONS, \
         VPN_BACKUP_LIST, VPN_BACKUP_CONTENT, VPN_BACKUP_EXPORT, \
         VPN_INTERFACE_HOSTS_CHANGE, \
         VPN_SETUP, \
         VPN_BACKUP_REMOVE, \
         VPN_MENU_ALL_HOSTS_INTERFACE, \
         VPN_TIMER, \
         VPN_BACKUP_EDIT, \
         VPN_BACKUP_HOST_EDIT, \
         WD_MAIN_MENU_LEVEL, \
         WD_ERRORS_LEVEL, \
         WD_ERR_SEARCH_ENGINES_LEVEL, \
         WD_ERR_INTERVAL_LEVEL, \
         WD_SITES_WATCH_LEVEL, \
         WD_SITES_ADD_LEVEL, \
         WD_SITES_EDIT_LINK_LEVEL, \
         WD_SITES_EDIT_LINK_INTERVAL_LEVEL,\
         ROUTER_MENU, \
         ROUTER_LIST_MENU = autoset(25)

# генерируем коды для кнопок меню в Telegram
# верхний уровень меню
MAIN_1_VPN_MENU_SHOW, \
    MAIN_2_ROUTER_ABOUT, \
    MAIN_3_ROUTER_MENU_SHOW, \
    MAIN_WHATCHDOGS_MENU_SHOW = autoset(4)
# уровень VPN меню
VPN_1_INTERFACE_LIST_SHOW, VPN_2_BACKUP_MENU_SHOW, VPN_3_SETUP_MENU_SHOW, VPN_4_BACK_ACTION = autoset(4)
# Меню выбора интерфейса
INL_1_INTERFACE_LIST_BUTTONS, INL_2_BACK_TO_MAIN_ACTION, INL_3_BACK_ACTION, INL_4_HOST_UPDATE_ACTION = autoset(4)
# Меню выбора доменных имен
WL_1_HOST_LIST_SHOW, \
    WL_2_HOST_ADD_REQUEST, WL_3_PURGE_REQUEST, WL_4_BACKUP_LIST_SHOW, \
    WL_5_REMOVE_ACCEPT_ACTION, WL_6_REMOVE_REJECT_ACTION, \
    WL_7_INTERFACE_CHANGE_REQUEST, WL_8_HOST_INFO_SHOW, \
    WL_9_BACK_TO_MAIN_ACTION, WL_10_BACK_ACTION, \
    WL_11_AUTO_SWITCH_ON_ACTION, WL_12_AUTO_SWITCH_OFF_ACTION, \
    WL_13_SELECT_ALL, WL_14_UNSELECT_ALL, WL_15_SAVE_ACTION \
    = autoset(15)
# Меню Архивов
BUP_1_BACKUP_LIST, \
    BUP_2_REMOVE_ACCEPT_ACTION, BUP_3_REMOVE_REJECT_ACTION, \
    BUP_4_CREATE_NEW_ACTION, BUP_5_DELETE, \
    BUP_6_BACK_TO_MAIN_ACTION, BUP_7_BACK_ACTION, \
    BUP_8_REMOVE_REQUEST, \
    = autoset(8)

# Меню смены интерфейса для выбранных хостов
IFCH_1_BACK_TO_MAIN_ACTION, IFCH_2_BACK_ACTION = autoset(2)

# Меню содержимого конкретного Архива
BCT_1_ADD_TO_WL_ACTION, \
    BCT_2_REMOVE_REQUEST, BCT_3_REMOVE_ACCEPT_ACTION, BCT_4_REMOVE_REJECT_ACTION, \
    BCT_5_SELECT_ALL, BCT_6_UNSELECT_ALL, BCT_7_RENAME_REQUEST, \
    BCT_8_BACK_TO_MAIN_ACTION, BCT_9_BACK_ACTION, \
    BCT_10_EXPORT_TO_WL_ACTION, BCT_11_BACK_INTERFACE_REQUEST, \
    = autoset(11)

# Меню установки таймера для обновления IP адресов хостов
TM_1_TIMER_SHOW, \
    TM_2_UPDATE_ACTION, \
    TM_3_CHANGE_REQUEST, \
    TM_4_DELETE_REQUEST, TM_5_DELETE_ACCEPT_ACTION, TM_6_REMOVE_REJECT_ACTION, \
    TM_7_BACK_TO_MAIN_ACTION, TM_8_BACK_ACTION, \
    = autoset(8)

WD_ERRORS_ALARM_MENU, \
    WD_CALLS_ALARM_MENU, \
    WD_INTERNET_ALARM_MENU, \
    WD_SITE_WATCHER_MENU, \
    WD_CHANGE_IP_ALERT_MENU, \
    WD_WIFI_CONNECT_ALARM_MENU, \
    WD_BACK_ACTION, \
    = autoset(7)

WD_ERR_ACTIVATION, \
    WD_ERR_INTERVAL_REQUEST, \
    WD_ERR_SEARCH_ENGINE_REQUEST, \
    WD_ERR_MAIN_MENU_BACK_ACTION, \
    WD_ERR_STEP_BACK_ACTION, \
    WD_ERR_BACK_TO_ERR_PAGE_ACTION, \
    = autoset(6)

WD_SITE_INTERVAL_REQUEST, \
    WD_SITE_LINK_LIST_REQUEST, \
    WD_SITE_LINK_ADD_REQUEST, \
    WD_SITE_LINK_DEL_REQUEST, \
    WD_SITE_LINK_DEL_ACCEPT, \
    WD_SITE_LINK_DEL_REJECT, \
    WD_SITE_LINK_DEL_ALL_REQUEST, \
    WD_SITE_LINK_DEL_ALL_ACCEPT, \
    WD_SITE_LINK_DEL_ALL_REJECT,\
    WD_SITE_MAIN_MENU_BACK_ACTION, \
    WD_SITE_STEP_BACK_ACTION, \
    = autoset(11)

WD_SITE_EDIT_LINK_WATCH_ACTIVATION, \
    WD_SITE_EDIT_LINK_DEL_REQUEST, \
    WD_SITE_EDIT_LINK_DEL_ACCEPT, \
    WD_SITE_EDIT_LINK_DEL_REJECT, \
    WD_SITE_EDIT_LINK_INTERVAL_REQUEST,\
    WD_SITE_EDIT_LINK_MAIN_MENU_BACK_ACTION, \
    WD_SITE_EDIT_LINK_STEP_BACK_ACTION,\
    WD_SITE_EDIT_INTERVAL_STEP_BACK_ACTION,\
    = autoset(8)
